version: '3'

services:
  app:
    image: chatbot-meta:1.0 //=> aca viene el nombre de imagen al crearla
    restart: on-failure //=> siempre que tu bot falle se reiniciara
    ports:
      - 3000:3008 //el primer 3000 representa el puerto del VPS y el segundo el puerto de tu contenedor
    environment:
      - jwtToken=${jwtToken}
      - numberId=${numberId}
      - verifyToken=${verifyToken}
      - Model=${Model}
      - Apikeia=${Apikeia}
      - spreadsheetId=${spreadsheetId}
      - privateKey=${privateKey}
      - clientEmail=${clientEmail}
